name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "7797ba78-933a-4d64-8afb-bda7c4f68519"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "d2a09f1fa09a484e839f66a9cea029c1"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
