name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "d039d06f-e85c-47aa-9539-db951c24016d"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "a4536268623e442ebbe0bd5067bfc1a0"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
